[2017-03-28 05:20:35,791]  dev.bankai@gmail.com already exists
System.Exception: See inner exception ---> Axis.Pollux.RBAC.Exceptions.AuthorizationException: See Inner Exception ---> System.Exception: dev.bankai@gmail.com already exists
   at BitDiamond.Core.Services.AccountManager.<>c__DisplayClass16_0.<RegisterUser>b__0() in C:\_dev\Jobs\BitDiamond\Dev\Git\BitDiamond.Core.Services\AccountManager.cs:line 85
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass12_0`1.<AuthorizeAccess>b__0() in C:\_dev\Projects\c#\Axis.Core\Axis.Pollux\Axis.Pollux.RoleAuthorization\Services\RoleAuthority.cs:line 130
   --- End of inner exception stack trace ---
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass12_0`1.<AuthorizeAccess>b__0() in C:\_dev\Projects\c#\Axis.Core\Axis.Pollux\Axis.Pollux.RoleAuthorization\Services\RoleAuthority.cs:line 138
   at Axis.Luna.Extensions.ObjectExtensions.Eval[R](Func`1 func, Func`2 error) in C:\_dev\Projects\c#\Axis.Core\Axis.Luna\Axis.Luna\Extensions\ObjectExtensions.cs:line 44
   --- End of inner exception stack trace ---
   at Axis.Luna.Extensions.ExceptionExtensions.Throw[R](Exception e) in C:\_dev\Projects\c#\Axis.Core\Axis.Luna\Axis.Luna\Extensions\ExceptionExtensions.cs:line 51
   at Axis.Luna.Operation.<>c__DisplayClass13_0`1.<Fail>b__0() in C:\_dev\Projects\c#\Axis.Core\Axis.Luna\Axis.Luna\Operation.cs:line 84
   at Axis.Luna.Operation`1..ctor(Func`1 func) in C:\_dev\Projects\c#\Axis.Core\Axis.Luna\Axis.Luna\Operation.cs:line 23



[2017-03-29 22:22:58,218]  System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote name could not be resolved: 'api.elasticemail.com'
   at System.Net.WebClient.UploadValues(Uri address, String method, NameValueCollection data)
   at System.Net.WebClient.UploadValues(String address, NameValueCollection data)
   at CAIRO.ElasticEmail.ElasticemailWebApi.<>c__DisplayClass4_0.<Send>b__1()
   at CAIRO.ElasticEmail.DefaultRetryStrategy.Try[T](Func`1 action, List`1 exceptions)
   --- End of inner exception stack trace ---
   at CAIRO.ElasticEmail.DefaultRetryStrategy.Try[T](Func`1 action, List`1 exceptions)
   at CAIRO.ElasticEmail.RetryLogic.Execute[T](Func`1 action)
   at CAIRO.ElasticEmail.ElasticemailWebApi.Send(ElasticemailMessage msg)
---> (Inner Exception #0) System.Net.WebException: The remote name could not be resolved: 'api.elasticemail.com'
   at System.Net.WebClient.UploadValues(Uri address, String method, NameValueCollection data)
   at System.Net.WebClient.UploadValues(String address, NameValueCollection data)
   at CAIRO.ElasticEmail.ElasticemailWebApi.<>c__DisplayClass4_0.<Send>b__1()
   at CAIRO.ElasticEmail.DefaultRetryStrategy.Try[T](Func`1 action, List`1 exceptions)<---

---> (Inner Exception #1) System.Net.WebException: The remote name could not be resolved: 'api.elasticemail.com'
   at System.Net.WebClient.UploadValues(Uri address, String method, NameValueCollection data)
   at System.Net.WebClient.UploadValues(String address, NameValueCollection data)
   at CAIRO.ElasticEmail.ElasticemailWebApi.<>c__DisplayClass4_0.<Send>b__1()
   at CAIRO.ElasticEmail.DefaultRetryStrategy.Try[T](Func`1 action, List`1 exceptions)<---

---> (Inner Exception #2) System.Net.WebException: The remote name could not be resolved: 'api.elasticemail.com'
   at System.Net.WebClient.UploadValues(Uri address, String method, NameValueCollection data)
   at System.Net.WebClient.UploadValues(String address, NameValueCollection data)
   at CAIRO.ElasticEmail.ElasticemailWebApi.<>c__DisplayClass4_0.<Send>b__1()
   at CAIRO.ElasticEmail.DefaultRetryStrategy.Try[T](Func`1 action, List`1 exceptions)<---

System.Exception: See inner exception ---> System.Exception: See inner exception ---> System.Exception: See inner exception ---> System.Exception: See inner exception ---> System.Exception: System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote name could not be resolved: 'api.elasticemail.com'
   at System.Net.WebClient.UploadValues(Uri address, String method, NameValueCollection data)
   at System.Net.WebClient.UploadValues(String address, NameValueCollection data)
   at CAIRO.ElasticEmail.ElasticemailWebApi.<>c__DisplayClass4_0.<Send>b__1()
   at CAIRO.ElasticEmail.DefaultRetryStrategy.Try[T](Func`1 action, List`1 exceptions)
   --- End of inner exception stack trace ---
   at CAIRO.ElasticEmail.DefaultRetryStrategy.Try[T](Func`1 action, List`1 exceptions)
   at CAIRO.ElasticEmail.RetryLogic.Execute[T](Func`1 action)
   at CAIRO.ElasticEmail.ElasticemailWebApi.Send(ElasticemailMessage msg)
---> (Inner Exception #0) System.Net.WebException: The remote name could not be resolved: 'api.elasticemail.com'
   at System.Net.WebClient.UploadValues(Uri address, String method, NameValueCollection data)
   at System.Net.WebClient.UploadValues(String address, NameValueCollection data)
   at CAIRO.ElasticEmail.ElasticemailWebApi.<>c__DisplayClass4_0.<Send>b__1()
   at CAIRO.ElasticEmail.DefaultRetryStrategy.Try[T](Func`1 action, List`1 exceptions)<---

---> (Inner Exception #1) System.Net.WebException: The remote name could not be resolved: 'api.elasticemail.com'
   at System.Net.WebClient.UploadValues(Uri address, String method, NameValueCollection data)
   at System.Net.WebClient.UploadValues(String address, NameValueCollection data)
   at CAIRO.ElasticEmail.ElasticemailWebApi.<>c__DisplayClass4_0.<Send>b__1()
   at CAIRO.ElasticEmail.DefaultRetryStrategy.Try[T](Func`1 action, List`1 exceptions)<---

---> (Inner Exception #2) System.Net.WebException: The remote name could not be resolved: 'api.elasticemail.com'
   at System.Net.WebClient.UploadValues(Uri address, String method, NameValueCollection data)
   at System.Net.WebClient.UploadValues(String address, NameValueCollection data)
   at CAIRO.ElasticEmail.ElasticemailWebApi.<>c__DisplayClass4_0.<Send>b__1()
   at CAIRO.ElasticEmail.DefaultRetryStrategy.Try[T](Func`1 action, List`1 exceptions)<---

   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Func`2 ex)
   at BitDiamond.Web.Infrastructure.Services.ElasticMailPushService.<>c__DisplayClass4_0.<SendMail>b__0() in C:\_dev\Jobs\BitDiamond\Dev\Git\BitDiamond.Web\Infrastructure\Services\ElasticMailPush.cs:line 77
   at Axis.Luna.Extensions.ObjectExtensions.Void(Action action)
   at Axis.Luna.Operation.<>c__DisplayClass0_0.<.ctor>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)
   --- End of inner exception stack trace ---
   at Axis.Luna.Extensions.ExceptionExtensions.Throw[R](Exception e)
   at Axis.Luna.Operation.<>c__DisplayClass13_0`1.<Fail>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)
   --- End of inner exception stack trace ---
   at Axis.Luna.Extensions.ExceptionExtensions.Throw[R](Exception e)
   at Axis.Luna.Operation.<>c__DisplayClass13_0`1.<Fail>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)
   --- End of inner exception stack trace ---
   at Axis.Luna.Extensions.ExceptionExtensions.Throw[R](Exception e)
   at Axis.Luna.Operation.<>c__DisplayClass13_0`1.<Fail>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)
   --- End of inner exception stack trace ---
   at Axis.Luna.Extensions.ExceptionExtensions.Throw[R](Exception e)
   at Axis.Luna.Operation.<>c__DisplayClass13_0`1.<Fail>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-02 14:59:19,492]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-02 15:21:06,299]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-02 15:21:06,300]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-02 15:21:06,299]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-02 15:21:06,307]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-02 15:21:06,405]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-02 15:21:06,418]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-02 15:21:07,485]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-02 15:54:20,551]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-02 18:36:24,524]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-02 20:04:17,661]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-02 20:26:43,732]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-02 20:26:43,733]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-02 20:26:43,735]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-02 20:26:43,748]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-02 20:26:43,748]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-02 20:26:43,748]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-02 20:29:51,810]  The remote name could not be resolved: 'blockchain.info'
System.Exception: See inner exception ---> Axis.Pollux.RBAC.Exceptions.AuthorizationException: See Inner Exception ---> System.Exception: See inner exception ---> System.Exception: See inner exception ---> System.Exception: See inner exception ---> Axis.Pollux.RBAC.Exceptions.AuthorizationException: See Inner Exception ---> System.Net.WebException: The remote name could not be resolved: 'blockchain.info'
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at System.Net.WebClient.DownloadString(String address)
   at BitDiamond.Core.Services.BlockChainService.<>c__DisplayClass10_0.<GetTransactionDetails>b__0() in C:\_dev\Jobs\BitDiamond\Dev\Git\BitDiamond.Core.Services\BlockChainService.cs:line 56
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass12_0`1.<AuthorizeAccess>b__0()
   --- End of inner exception stack trace ---
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass12_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Extensions.ObjectExtensions.Eval[R](Func`1 func, Func`2 error)
   --- End of inner exception stack trace ---
   at Axis.Luna.Extensions.ExceptionExtensions.Throw[R](Exception e)
   at Axis.Luna.Operation.<>c__DisplayClass13_0`1.<Fail>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)
   --- End of inner exception stack trace ---
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Luna.Operation`1.Resolve()
   at BitDiamond.Core.Services.BlockChainService.<>c__DisplayClass20_0.<VerifyTransaction>b__0() in C:\_dev\Jobs\BitDiamond\Dev\Git\BitDiamond.Core.Services\BlockChainService.cs:line 178
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass9_0.<AuthorizeAccess>b__0()
   at Axis.Luna.Extensions.ObjectExtensions.Void(Action action)
   at Axis.Luna.Operation.<>c__DisplayClass0_0.<.ctor>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)
   --- End of inner exception stack trace ---
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Luna.Operation`1.Resolve()
   at BitDiamond.Core.Services.BitLevelManager.<>c__DisplayClass13_0.<VerifyAndSaveTransactionHash>b__0() in C:\_dev\Jobs\BitDiamond\Dev\Git\BitDiamond.Core.Services\BitLevelManager.cs:line 146
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass12_0`1.<AuthorizeAccess>b__0()
   --- End of inner exception stack trace ---
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass12_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Extensions.ObjectExtensions.Eval[R](Func`1 func, Func`2 error)
   --- End of inner exception stack trace ---
   at Axis.Luna.Extensions.ExceptionExtensions.Throw[R](Exception e)
   at Axis.Luna.Operation.<>c__DisplayClass13_0`1.<Fail>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-02 20:30:37,590]  The remote name could not be resolved: 'blockchain.info'
System.Exception: See inner exception ---> Axis.Pollux.RBAC.Exceptions.AuthorizationException: See Inner Exception ---> System.Exception: See inner exception ---> System.Exception: See inner exception ---> System.Exception: See inner exception ---> Axis.Pollux.RBAC.Exceptions.AuthorizationException: See Inner Exception ---> System.Net.WebException: The remote name could not be resolved: 'blockchain.info'
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at System.Net.WebClient.DownloadString(String address)
   at BitDiamond.Core.Services.BlockChainService.<>c__DisplayClass10_0.<GetTransactionDetails>b__0() in C:\_dev\Jobs\BitDiamond\Dev\Git\BitDiamond.Core.Services\BlockChainService.cs:line 56
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass12_0`1.<AuthorizeAccess>b__0()
   --- End of inner exception stack trace ---
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass12_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Extensions.ObjectExtensions.Eval[R](Func`1 func, Func`2 error)
   --- End of inner exception stack trace ---
   at Axis.Luna.Extensions.ExceptionExtensions.Throw[R](Exception e)
   at Axis.Luna.Operation.<>c__DisplayClass13_0`1.<Fail>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)
   --- End of inner exception stack trace ---
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Luna.Operation`1.Resolve()
   at BitDiamond.Core.Services.BlockChainService.<>c__DisplayClass20_0.<VerifyTransaction>b__0() in C:\_dev\Jobs\BitDiamond\Dev\Git\BitDiamond.Core.Services\BlockChainService.cs:line 178
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass9_0.<AuthorizeAccess>b__0()
   at Axis.Luna.Extensions.ObjectExtensions.Void(Action action)
   at Axis.Luna.Operation.<>c__DisplayClass0_0.<.ctor>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)
   --- End of inner exception stack trace ---
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Luna.Operation`1.Resolve()
   at BitDiamond.Core.Services.BitLevelManager.<>c__DisplayClass13_0.<VerifyAndSaveTransactionHash>b__0() in C:\_dev\Jobs\BitDiamond\Dev\Git\BitDiamond.Core.Services\BitLevelManager.cs:line 146
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass12_0`1.<AuthorizeAccess>b__0()
   --- End of inner exception stack trace ---
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass12_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Extensions.ObjectExtensions.Eval[R](Func`1 func, Func`2 error)
   --- End of inner exception stack trace ---
   at Axis.Luna.Extensions.ExceptionExtensions.Throw[R](Exception e)
   at Axis.Luna.Operation.<>c__DisplayClass13_0`1.<Fail>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-02 20:59:26,536]  The remote name could not be resolved: 'blockchain.info'
System.Exception: See inner exception ---> System.Exception: See inner exception ---> System.Exception: See inner exception ---> Axis.Pollux.RBAC.Exceptions.AuthorizationException: See Inner Exception ---> System.Net.WebException: The remote name could not be resolved: 'blockchain.info'
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at System.Net.WebClient.DownloadString(String address)
   at BitDiamond.Core.Services.BlockChainService.<>c__DisplayClass10_0.<GetTransactionDetails>b__0() in C:\_dev\Jobs\BitDiamond\Dev\Git\BitDiamond.Core.Services\BlockChainService.cs:line 56
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass12_0`1.<AuthorizeAccess>b__0()
   --- End of inner exception stack trace ---
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass12_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Extensions.ObjectExtensions.Eval[R](Func`1 func, Func`2 error)
   --- End of inner exception stack trace ---
   at Axis.Luna.Extensions.ExceptionExtensions.Throw[R](Exception e)
   at Axis.Luna.Operation.<>c__DisplayClass13_0`1.<Fail>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)
   --- End of inner exception stack trace ---
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Luna.Operation`1.Resolve()
   at BitDiamond.Core.Services.BitLevelManager.<ConfirmUpgradeDonnation>b__15_0() in C:\_dev\Jobs\BitDiamond\Dev\Git\BitDiamond.Core.Services\BitLevelManager.cs:line 239
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)
   --- End of inner exception stack trace ---
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Luna.Operation`1.Resolve()
   at BitDiamond.Core.Services.BitLevelManager.<Upgrade>b__12_0() in C:\_dev\Jobs\BitDiamond\Dev\Git\BitDiamond.Core.Services\BitLevelManager.cs:line 64
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-02 21:00:42,856]  The remote name could not be resolved: 'blockchain.info'
System.Exception: See inner exception ---> System.Exception: See inner exception ---> System.Exception: See inner exception ---> Axis.Pollux.RBAC.Exceptions.AuthorizationException: See Inner Exception ---> System.Net.WebException: The remote name could not be resolved: 'blockchain.info'
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at System.Net.WebClient.DownloadString(String address)
   at BitDiamond.Core.Services.BlockChainService.<>c__DisplayClass10_0.<GetTransactionDetails>b__0() in C:\_dev\Jobs\BitDiamond\Dev\Git\BitDiamond.Core.Services\BlockChainService.cs:line 56
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass12_0`1.<AuthorizeAccess>b__0()
   --- End of inner exception stack trace ---
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass12_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Extensions.ObjectExtensions.Eval[R](Func`1 func, Func`2 error)
   --- End of inner exception stack trace ---
   at Axis.Luna.Extensions.ExceptionExtensions.Throw[R](Exception e)
   at Axis.Luna.Operation.<>c__DisplayClass13_0`1.<Fail>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)
   --- End of inner exception stack trace ---
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Luna.Operation`1.Resolve()
   at BitDiamond.Core.Services.BitLevelManager.<ConfirmUpgradeDonnation>b__15_0() in C:\_dev\Jobs\BitDiamond\Dev\Git\BitDiamond.Core.Services\BitLevelManager.cs:line 239
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)
   --- End of inner exception stack trace ---
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Luna.Operation`1.Resolve()
   at BitDiamond.Core.Services.BitLevelManager.<Upgrade>b__12_0() in C:\_dev\Jobs\BitDiamond\Dev\Git\BitDiamond.Core.Services\BitLevelManager.cs:line 64
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-02 21:01:49,967]  The remote name could not be resolved: 'blockchain.info'
System.Exception: See inner exception ---> System.Exception: See inner exception ---> System.Exception: See inner exception ---> Axis.Pollux.RBAC.Exceptions.AuthorizationException: See Inner Exception ---> System.Net.WebException: The remote name could not be resolved: 'blockchain.info'
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at System.Net.WebClient.DownloadString(String address)
   at BitDiamond.Core.Services.BlockChainService.<>c__DisplayClass10_0.<GetTransactionDetails>b__0() in C:\_dev\Jobs\BitDiamond\Dev\Git\BitDiamond.Core.Services\BlockChainService.cs:line 56
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass12_0`1.<AuthorizeAccess>b__0()
   --- End of inner exception stack trace ---
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass12_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Extensions.ObjectExtensions.Eval[R](Func`1 func, Func`2 error)
   --- End of inner exception stack trace ---
   at Axis.Luna.Extensions.ExceptionExtensions.Throw[R](Exception e)
   at Axis.Luna.Operation.<>c__DisplayClass13_0`1.<Fail>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)
   --- End of inner exception stack trace ---
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Luna.Operation`1.Resolve()
   at BitDiamond.Core.Services.BitLevelManager.<ConfirmUpgradeDonnation>b__15_0() in C:\_dev\Jobs\BitDiamond\Dev\Git\BitDiamond.Core.Services\BitLevelManager.cs:line 239
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)
   --- End of inner exception stack trace ---
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Luna.Operation`1.Resolve()
   at BitDiamond.Core.Services.BitLevelManager.<Upgrade>b__12_0() in C:\_dev\Jobs\BitDiamond\Dev\Git\BitDiamond.Core.Services\BitLevelManager.cs:line 64
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-03 12:45:00,867]  This address has already been used
System.Exception: See inner exception ---> Axis.Pollux.RBAC.Exceptions.AuthorizationException: See Inner Exception ---> System.Exception: This address has already been used
   at BitDiamond.Core.Services.BitLevelManager.<>c__DisplayClass22_0.<AddBitcoindAddress>b__0() in C:\_dev\Jobs\BitDiamond\Dev\Git\BitDiamond.Core.Services\BitLevelManager.cs:line 297
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass12_0`1.<AuthorizeAccess>b__0()
   --- End of inner exception stack trace ---
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass12_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Extensions.ObjectExtensions.Eval[R](Func`1 func, Func`2 error)
   --- End of inner exception stack trace ---
   at Axis.Luna.Extensions.ExceptionExtensions.Throw[R](Exception e)
   at Axis.Luna.Operation.<>c__DisplayClass13_0`1.<Fail>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-10 09:50:35,172]  Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at BitDiamond.Core.Services.BitLevelManager.<>c__DisplayClass14_0.<Promote>b__0() in C:\_dev\Jobs\BitDiamond\Dev\Git\BitDiamond.Core.Services\BitLevelManager.cs:line 162
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-10 09:51:09,021]  Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at BitDiamond.Core.Services.BitLevelManager.<>c__DisplayClass14_0.<Promote>b__0() in C:\_dev\Jobs\BitDiamond\Dev\Git\BitDiamond.Core.Services\BitLevelManager.cs:line 162
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-13 07:22:17,407]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-13 07:22:17,418]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-13 07:22:17,420]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-13 07:22:17,851]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-13 07:22:18,316]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-13 07:27:40,809]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-13 07:27:40,810]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-13 07:27:40,810]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-13 07:27:40,810]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-13 07:27:40,846]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-13 07:27:41,264]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-13 07:28:06,713]  invalid logon
System.Exception: invalid logon
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIfNull[R](R value, Exception ex)
   at BitDiamond.Core.Services.AccountManager.<ValidateUserLogon>b__38_0() in C:\_dev\Jobs\BitDiamond\Dev\Git\BitDiamond.Core.Services\AccountManager.cs:line 582
   at Axis.Luna.Extensions.ObjectExtensions.Void(Action action)
   at Axis.Luna.Operation.<>c__DisplayClass0_0.<.ctor>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-13 07:28:08,089]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-13 07:28:08,089]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-13 07:28:08,143]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-13 07:28:08,144]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-13 10:49:20,564]  invalid logon
System.Exception: invalid logon
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIfNull[R](R value, Exception ex)
   at BitDiamond.Core.Services.AccountManager.<ValidateUserLogon>b__38_0() in C:\_dev\Jobs\BitDiamond\Dev\Git\BitDiamond.Core.Services\AccountManager.cs:line 582
   at Axis.Luna.Extensions.ObjectExtensions.Void(Action action)
   at Axis.Luna.Operation.<>c__DisplayClass0_0.<.ctor>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-13 11:07:34,498]  invalid logon
System.Exception: invalid logon
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIfNull[R](R value, Exception ex)
   at BitDiamond.Core.Services.AccountManager.<ValidateUserLogon>b__38_0() in C:\_dev\Jobs\BitDiamond\Dev\Git\BitDiamond.Core.Services\AccountManager.cs:line 582
   at Axis.Luna.Extensions.ObjectExtensions.Void(Action action)
   at Axis.Luna.Operation.<>c__DisplayClass0_0.<.ctor>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-13 11:21:51,570]  invalid logon
System.Exception: invalid logon
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIfNull[R](R value, Exception ex)
   at BitDiamond.Core.Services.AccountManager.<ValidateUserLogon>b__38_0() in C:\_dev\Jobs\BitDiamond\Dev\Git\BitDiamond.Core.Services\AccountManager.cs:line 582
   at Axis.Luna.Extensions.ObjectExtensions.Void(Action action)
   at Axis.Luna.Operation.<>c__DisplayClass0_0.<.ctor>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-13 11:21:58,332]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-13 11:21:58,333]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-13 11:21:58,334]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-13 11:21:58,357]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-13 11:38:36,987]  invalid logon
System.Exception: invalid logon
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIfNull[R](R value, Exception ex)
   at BitDiamond.Core.Services.AccountManager.<ValidateUserLogon>b__38_0() in C:\_dev\Jobs\BitDiamond\Dev\Git\BitDiamond.Core.Services\AccountManager.cs:line 582
   at Axis.Luna.Extensions.ObjectExtensions.Void(Action action)
   at Axis.Luna.Operation.<>c__DisplayClass0_0.<.ctor>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-15 10:25:25,932]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-15 13:41:01,129]  Access Denied
System.Exception: See inner exception ---> Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass12_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Extensions.ObjectExtensions.Eval[R](Func`1 func, Func`2 error)
   --- End of inner exception stack trace ---
   at Axis.Luna.Extensions.ExceptionExtensions.Throw[R](Exception e)
   at Axis.Luna.Operation.<>c__DisplayClass13_0`1.<Fail>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-15 19:43:53,328]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-15 19:43:53,343]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-15 19:43:53,355]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-15 19:43:53,352]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-15 19:43:53,692]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-15 19:43:53,742]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-15 19:43:53,826]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-15 19:44:46,131]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-15 19:44:46,131]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-15 19:44:46,139]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-15 19:44:46,140]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-15 19:44:46,283]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-15 19:44:46,553]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-15 19:47:48,675]  invalid receiver
System.Exception: See inner exception ---> Axis.Pollux.RBAC.Exceptions.AuthorizationException: See Inner Exception ---> System.Exception: See inner exception ---> System.Exception: See inner exception ---> System.Exception: See inner exception ---> Axis.Pollux.RBAC.Exceptions.AuthorizationException: See Inner Exception ---> System.Exception: invalid receiver
   at BitDiamond.Core.Services.BlockChainService.<>c__DisplayClass10_0.<AcquireTransactionDetails>b__0() in C:\_dev\Jobs\BitDiamond\Dev\Git\BitDiamond.Core.Services\BlockChainService.cs:line 65
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass12_0`1.<AuthorizeAccess>b__0()
   --- End of inner exception stack trace ---
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass12_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Extensions.ObjectExtensions.Eval[R](Func`1 func, Func`2 error)
   --- End of inner exception stack trace ---
   at Axis.Luna.Extensions.ExceptionExtensions.Throw[R](Exception e)
   at Axis.Luna.Operation.<>c__DisplayClass13_0`1.<Fail>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)
   --- End of inner exception stack trace ---
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Luna.Operation`1.Resolve()
   at BitDiamond.Core.Services.BlockChainService.<>c__DisplayClass20_0.<VerifyTransaction>b__0() in C:\_dev\Jobs\BitDiamond\Dev\Git\BitDiamond.Core.Services\BlockChainService.cs:line 178
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass9_0.<AuthorizeAccess>b__0()
   at Axis.Luna.Extensions.ObjectExtensions.Void(Action action)
   at Axis.Luna.Operation.<>c__DisplayClass0_0.<.ctor>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)
   --- End of inner exception stack trace ---
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Luna.Operation`1.Resolve()
   at BitDiamond.Core.Services.BitLevelManager.<>c__DisplayClass16_0.<VerifyAndSaveTransactionHash>b__0() in C:\_dev\Jobs\BitDiamond\Dev\Git\BitDiamond.Core.Services\BitLevelManager.cs:line 158
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass12_0`1.<AuthorizeAccess>b__0()
   --- End of inner exception stack trace ---
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass12_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Extensions.ObjectExtensions.Eval[R](Func`1 func, Func`2 error)
   --- End of inner exception stack trace ---
   at Axis.Luna.Extensions.ExceptionExtensions.Throw[R](Exception e)
   at Axis.Luna.Operation.<>c__DisplayClass13_0`1.<Fail>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-15 19:54:49,758]  invalid receiver
System.Exception: See inner exception ---> Axis.Pollux.RBAC.Exceptions.AuthorizationException: See Inner Exception ---> System.Exception: See inner exception ---> System.Exception: See inner exception ---> System.Exception: See inner exception ---> Axis.Pollux.RBAC.Exceptions.AuthorizationException: See Inner Exception ---> System.Exception: invalid receiver
   at BitDiamond.Core.Services.BlockChainService.<>c__DisplayClass10_0.<AcquireTransactionDetails>b__0() in C:\_dev\Jobs\BitDiamond\Dev\Git\BitDiamond.Core.Services\BlockChainService.cs:line 65
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass12_0`1.<AuthorizeAccess>b__0()
   --- End of inner exception stack trace ---
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass12_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Extensions.ObjectExtensions.Eval[R](Func`1 func, Func`2 error)
   --- End of inner exception stack trace ---
   at Axis.Luna.Extensions.ExceptionExtensions.Throw[R](Exception e)
   at Axis.Luna.Operation.<>c__DisplayClass13_0`1.<Fail>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)
   --- End of inner exception stack trace ---
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Luna.Operation`1.Resolve()
   at BitDiamond.Core.Services.BlockChainService.<>c__DisplayClass20_0.<VerifyTransaction>b__0() in C:\_dev\Jobs\BitDiamond\Dev\Git\BitDiamond.Core.Services\BlockChainService.cs:line 178
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass9_0.<AuthorizeAccess>b__0()
   at Axis.Luna.Extensions.ObjectExtensions.Void(Action action)
   at Axis.Luna.Operation.<>c__DisplayClass0_0.<.ctor>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)
   --- End of inner exception stack trace ---
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Luna.Operation`1.Resolve()
   at BitDiamond.Core.Services.BitLevelManager.<>c__DisplayClass16_0.<VerifyAndSaveTransactionHash>b__0() in C:\_dev\Jobs\BitDiamond\Dev\Git\BitDiamond.Core.Services\BitLevelManager.cs:line 158
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass12_0`1.<AuthorizeAccess>b__0()
   --- End of inner exception stack trace ---
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass12_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Extensions.ObjectExtensions.Eval[R](Func`1 func, Func`2 error)
   --- End of inner exception stack trace ---
   at Axis.Luna.Extensions.ExceptionExtensions.Throw[R](Exception e)
   at Axis.Luna.Operation.<>c__DisplayClass13_0`1.<Fail>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-15 20:22:57,263]  Access Denied
System.Exception: See inner exception ---> Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass12_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Extensions.ObjectExtensions.Eval[R](Func`1 func, Func`2 error)
   --- End of inner exception stack trace ---
   at Axis.Luna.Extensions.ExceptionExtensions.Throw[R](Exception e)
   at Axis.Luna.Operation.<>c__DisplayClass13_0`1.<Fail>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-15 20:29:01,229]  invalid receiver
System.Exception: See inner exception ---> Axis.Pollux.RBAC.Exceptions.AuthorizationException: See Inner Exception ---> System.Exception: See inner exception ---> System.Exception: See inner exception ---> System.Exception: See inner exception ---> Axis.Pollux.RBAC.Exceptions.AuthorizationException: See Inner Exception ---> System.Exception: invalid receiver
   at BitDiamond.Core.Services.BlockChainService.<>c__DisplayClass10_0.<AcquireTransactionDetails>b__0() in C:\_dev\Jobs\BitDiamond\Dev\Git\BitDiamond.Core.Services\BlockChainService.cs:line 65
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass12_0`1.<AuthorizeAccess>b__0()
   --- End of inner exception stack trace ---
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass12_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Extensions.ObjectExtensions.Eval[R](Func`1 func, Func`2 error)
   --- End of inner exception stack trace ---
   at Axis.Luna.Extensions.ExceptionExtensions.Throw[R](Exception e)
   at Axis.Luna.Operation.<>c__DisplayClass13_0`1.<Fail>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)
   --- End of inner exception stack trace ---
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Luna.Operation`1.Resolve()
   at BitDiamond.Core.Services.BlockChainService.<>c__DisplayClass20_0.<VerifyTransaction>b__0() in C:\_dev\Jobs\BitDiamond\Dev\Git\BitDiamond.Core.Services\BlockChainService.cs:line 178
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass9_0.<AuthorizeAccess>b__0()
   at Axis.Luna.Extensions.ObjectExtensions.Void(Action action)
   at Axis.Luna.Operation.<>c__DisplayClass0_0.<.ctor>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)
   --- End of inner exception stack trace ---
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Luna.Operation`1.Resolve()
   at BitDiamond.Core.Services.BitLevelManager.<>c__DisplayClass16_0.<VerifyAndSaveTransactionHash>b__0() in C:\_dev\Jobs\BitDiamond\Dev\Git\BitDiamond.Core.Services\BitLevelManager.cs:line 158
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass12_0`1.<AuthorizeAccess>b__0()
   --- End of inner exception stack trace ---
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass12_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Extensions.ObjectExtensions.Eval[R](Func`1 func, Func`2 error)
   --- End of inner exception stack trace ---
   at Axis.Luna.Extensions.ExceptionExtensions.Throw[R](Exception e)
   at Axis.Luna.Operation.<>c__DisplayClass13_0`1.<Fail>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-15 21:01:49,336]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-15 21:01:49,351]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-15 21:01:49,351]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-15 21:01:49,481]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-15 21:01:50,094]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-15 21:01:50,169]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-15 21:01:50,188]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-15 21:01:50,324]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-15 21:01:50,324]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-15 21:01:50,324]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-15 21:01:50,373]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-15 21:01:50,664]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-15 21:01:51,370]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-15 21:12:19,349]  The remote name could not be resolved: 'blockchain.info'
System.Exception: See inner exception ---> Axis.Pollux.RBAC.Exceptions.AuthorizationException: See Inner Exception ---> System.Exception: See inner exception ---> System.Exception: See inner exception ---> System.Exception: See inner exception ---> Axis.Pollux.RBAC.Exceptions.AuthorizationException: See Inner Exception ---> System.Net.WebException: The remote name could not be resolved: 'blockchain.info'
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at System.Net.WebClient.DownloadString(String address)
   at BitDiamond.Core.Services.BlockChainService.<>c__DisplayClass10_0.<AcquireTransactionDetails>b__0() in C:\_dev\Jobs\BitDiamond\Dev\Git\BitDiamond.Core.Services\BlockChainService.cs:line 56
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass12_0`1.<AuthorizeAccess>b__0()
   --- End of inner exception stack trace ---
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass12_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Extensions.ObjectExtensions.Eval[R](Func`1 func, Func`2 error)
   --- End of inner exception stack trace ---
   at Axis.Luna.Extensions.ExceptionExtensions.Throw[R](Exception e)
   at Axis.Luna.Operation.<>c__DisplayClass13_0`1.<Fail>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)
   --- End of inner exception stack trace ---
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Luna.Operation`1.Resolve()
   at BitDiamond.Core.Services.BlockChainService.<>c__DisplayClass20_0.<VerifyTransaction>b__0() in C:\_dev\Jobs\BitDiamond\Dev\Git\BitDiamond.Core.Services\BlockChainService.cs:line 178
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass9_0.<AuthorizeAccess>b__0()
   at Axis.Luna.Extensions.ObjectExtensions.Void(Action action)
   at Axis.Luna.Operation.<>c__DisplayClass0_0.<.ctor>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)
   --- End of inner exception stack trace ---
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Luna.Operation`1.Resolve()
   at BitDiamond.Core.Services.BitLevelManager.<>c__DisplayClass16_0.<VerifyAndSaveTransactionHash>b__0() in C:\_dev\Jobs\BitDiamond\Dev\Git\BitDiamond.Core.Services\BitLevelManager.cs:line 158
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass12_0`1.<AuthorizeAccess>b__0()
   --- End of inner exception stack trace ---
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass12_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Extensions.ObjectExtensions.Eval[R](Func`1 func, Func`2 error)
   --- End of inner exception stack trace ---
   at Axis.Luna.Extensions.ExceptionExtensions.Throw[R](Exception e)
   at Axis.Luna.Operation.<>c__DisplayClass13_0`1.<Fail>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-15 21:15:34,594]  invalid amount
System.Exception: See inner exception ---> Axis.Pollux.RBAC.Exceptions.AuthorizationException: See Inner Exception ---> System.Exception: See inner exception ---> System.Exception: See inner exception ---> System.Exception: See inner exception ---> Axis.Pollux.RBAC.Exceptions.AuthorizationException: See Inner Exception ---> System.Exception: invalid amount
   at BitDiamond.Core.Services.BlockChainService.<>c__DisplayClass10_0.<AcquireTransactionDetails>b__0() in C:\_dev\Jobs\BitDiamond\Dev\Git\BitDiamond.Core.Services\BlockChainService.cs:line 72
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass12_0`1.<AuthorizeAccess>b__0()
   --- End of inner exception stack trace ---
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass12_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Extensions.ObjectExtensions.Eval[R](Func`1 func, Func`2 error)
   --- End of inner exception stack trace ---
   at Axis.Luna.Extensions.ExceptionExtensions.Throw[R](Exception e)
   at Axis.Luna.Operation.<>c__DisplayClass13_0`1.<Fail>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)
   --- End of inner exception stack trace ---
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Luna.Operation`1.Resolve()
   at BitDiamond.Core.Services.BlockChainService.<>c__DisplayClass20_0.<VerifyTransaction>b__0() in C:\_dev\Jobs\BitDiamond\Dev\Git\BitDiamond.Core.Services\BlockChainService.cs:line 178
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass9_0.<AuthorizeAccess>b__0()
   at Axis.Luna.Extensions.ObjectExtensions.Void(Action action)
   at Axis.Luna.Operation.<>c__DisplayClass0_0.<.ctor>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)
   --- End of inner exception stack trace ---
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Luna.Operation`1.Resolve()
   at BitDiamond.Core.Services.BitLevelManager.<>c__DisplayClass16_0.<VerifyAndSaveTransactionHash>b__0() in C:\_dev\Jobs\BitDiamond\Dev\Git\BitDiamond.Core.Services\BitLevelManager.cs:line 158
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass12_0`1.<AuthorizeAccess>b__0()
   --- End of inner exception stack trace ---
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass12_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Extensions.ObjectExtensions.Eval[R](Func`1 func, Func`2 error)
   --- End of inner exception stack trace ---
   at Axis.Luna.Extensions.ExceptionExtensions.Throw[R](Exception e)
   at Axis.Luna.Operation.<>c__DisplayClass13_0`1.<Fail>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-19 15:58:42,293]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-19 15:58:42,314]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-19 15:58:42,337]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-19 15:58:42,535]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-19 15:58:42,691]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-19 15:58:42,816]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-19 15:58:42,898]  Access Denied
Axis.Pollux.RBAC.Exceptions.AuthorizationException: Access Denied
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Pollux.RBAC.Services.RoleAuthority.ValidatePermissionProfile(PermissionProfile authRequest)
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass10_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-19 15:59:14,744]  The constructor of type HangfireJobScheduler contains the parameter with name 'connection' and type IStorageConnection that is not registered. Please ensure IStorageConnection is registered, or change the constructor of HangfireJobScheduler.
System.Exception: See inner exception ---> Axis.Pollux.RBAC.Exceptions.AuthorizationException: See Inner Exception ---> SimpleInjector.ActivationException: The constructor of type HangfireJobScheduler contains the parameter with name 'connection' and type IStorageConnection that is not registered. Please ensure IStorageConnection is registered, or change the constructor of HangfireJobScheduler.
   at SimpleInjector.Container.ThrowParameterTypeMustBeRegistered(InjectionTargetInfo target)
   at SimpleInjector.Advanced.DefaultDependencyInjectionBehavior.GetInstanceProducerFor(InjectionConsumerInfo consumer)
   at SimpleInjector.Advanced.DefaultDependencyInjectionBehavior.BuildExpression(InjectionConsumerInfo consumer)
   at SimpleInjector.ContainerOptions.BuildParameterExpression(InjectionConsumerInfo consumer)
   at SimpleInjector.Registration.BuildConstructorParameters(Type serviceType, Type implementationType, ConstructorInfo constructor)
   at SimpleInjector.Registration.BuildNewExpression(Type serviceType, Type implementationType)
   at SimpleInjector.Registration.BuildTransientExpression[TService,TImplementation]()
   at SimpleInjector.Registration.BuildTransientDelegate[TService,TImplementation]()
   at SimpleInjector.Lifestyles.ScopedRegistration`2.BuildInstanceCreator()
   at SimpleInjector.Lifestyles.ScopedRegistration`2.BuildExpression()
   at SimpleInjector.Registration.BuildExpression(InstanceProducer producer)
   at SimpleInjector.InstanceProducer.BuildExpressionInternal()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at SimpleInjector.InstanceProducer.BuildInstanceCreator()
   at SimpleInjector.InstanceProducer.BuildAndReplaceInstanceCreatorAndCreateFirstInstance()
   at SimpleInjector.InstanceProducer.GetInstance()
   at SimpleInjector.Container.GetInstanceForRootType(Type serviceType)
   at SimpleInjector.Container.GetInstance(Type serviceType)
   at BitDiamond.Web.Infrastructure.DI.SimpleContainerResolver.Resolve[Service](Object[] args) in C:\_dev\Jobs\BitDiamond\Dev\Git\BitDiamond.Web\Infrastructure\DI\ServiceInterceptor.cs:line 56
   at BitDiamond.Web.Infrastructure.DI.ServiceInterceptor`1.Intercept(IInvocation invocation) in C:\_dev\Jobs\BitDiamond\Dev\Git\BitDiamond.Web\Infrastructure\DI\ServiceInterceptor.cs:line 34
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.ILazyServiceFakerProxy_19.RepeatOperation(IUserContext principal, Expression`1 opInvocation, ScheduleInterval interval)
   at BitDiamond.Core.Services.BitLevelManager.<VerifyAndSaveTransactionHash>b__16_2(Operation`1 opr) in C:\_dev\Jobs\BitDiamond\Dev\Git\BitDiamond.Core.Services\BitLevelManager.cs:line 168
   at Axis.Luna.Extensions.OperationExtensions.Then[In,Out](Operation`1 op, Func`2 func)
   at BitDiamond.Core.Services.BitLevelManager.<>c__DisplayClass16_0.<VerifyAndSaveTransactionHash>b__0() in C:\_dev\Jobs\BitDiamond\Dev\Git\BitDiamond.Core.Services\BitLevelManager.cs:line 161
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass12_0`1.<AuthorizeAccess>b__0()
   --- End of inner exception stack trace ---
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass12_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Extensions.ObjectExtensions.Eval[R](Func`1 func, Func`2 error)
   --- End of inner exception stack trace ---
   at Axis.Luna.Extensions.ExceptionExtensions.Throw[R](Exception e)
   at Axis.Luna.Operation.<>c__DisplayClass13_0`1.<Fail>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-19 22:06:10,183]  The remote name could not be resolved: 'blockchain.info'
System.Exception: See inner exception ---> System.Exception: See inner exception ---> System.Exception: See inner exception ---> System.Exception: See inner exception ---> Axis.Pollux.RBAC.Exceptions.AuthorizationException: See Inner Exception ---> System.Net.WebException: The remote name could not be resolved: 'blockchain.info'
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at System.Net.WebClient.DownloadString(String address)
   at BitDiamond.Core.Services.BlockChainService.<>c__DisplayClass10_0.<AcquireTransactionDetails>b__0() in C:\_dev\Jobs\BitDiamond\Dev\Git\BitDiamond.Core.Services\BlockChainService.cs:line 56
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass12_0`1.<AuthorizeAccess>b__0()
   --- End of inner exception stack trace ---
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass12_0`1.<AuthorizeAccess>b__0()
   at Axis.Luna.Extensions.ObjectExtensions.Eval[R](Func`1 func, Func`2 error)
   --- End of inner exception stack trace ---
   at Axis.Luna.Extensions.ExceptionExtensions.Throw[R](Exception e)
   at Axis.Luna.Operation.<>c__DisplayClass13_0`1.<Fail>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)
   --- End of inner exception stack trace ---
   at Axis.Luna.Extensions.ExceptionExtensions.ThrowIf[R](R value, Func`2 predicate, Exception ex)
   at Axis.Luna.Operation`1.Resolve()
   at BitDiamond.Core.Services.BlockChainService.<>c__DisplayClass20_0.<VerifyTransaction>b__0() in C:\_dev\Jobs\BitDiamond\Dev\Git\BitDiamond.Core.Services\BlockChainService.cs:line 178
   at Axis.Pollux.RBAC.Services.RoleAuthority.<>c__DisplayClass9_0.<AuthorizeAccess>b__0()
   at Axis.Luna.Extensions.ObjectExtensions.Void(Action action)
   at Axis.Luna.Operation.<>c__DisplayClass0_0.<.ctor>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)
   --- End of inner exception stack trace ---
   at Axis.Luna.Extensions.ExceptionExtensions.Throw[R](Exception e)
   at Axis.Luna.Operation.<>c__DisplayClass13_0`1.<Fail>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)
   --- End of inner exception stack trace ---
   at Axis.Luna.Extensions.ExceptionExtensions.Throw[R](Exception e)
   at Axis.Luna.Operation.<>c__DisplayClass13_0`1.<Fail>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-20 12:22:29,530]  The process cannot access the file 'C:\_dev\Jobs\BitDiamond\Dev\Git\BitDiamond.Web\App_Data\pad.json' because it is being used by another process.
System.IO.IOException: The process cannot access the file 'C:\_dev\Jobs\BitDiamond\Dev\Git\BitDiamond.Web\App_Data\pad.json' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at BitDiamond.Web.Controllers.Api.BlockChainController.<>c.<GetSystemTransactionsTotal>b__7_1(Operation`1 opr) in C:\_dev\Jobs\BitDiamond\Dev\Git\BitDiamond.Web\Controllers\Api\BlockChainController.cs:line 64
   at Axis.Luna.Extensions.OperationExtensions.<>c__DisplayClass3_0`2.<Then>b__0()
   at Axis.Luna.Operation`1..ctor(Func`1 func)



[2017-04-24 08:54:42,316]  Error occurred during execution of 'Worker #e5625194' process. Execution will be retried (attempt #4) in 00:00:11 seconds.
System.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: Shared Memory Provider, error: 0 - No process is on the other end of the pipe.) ---> System.ComponentModel.Win32Exception (0x80004005): No process is on the other end of the pipe
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Hangfire.SqlServer.SqlServerStorage.CreateAndOpenConnection()
   at Hangfire.SqlServer.SqlServerJobQueue.Dequeue(String[] queues, CancellationToken cancellationToken)
   at Hangfire.SqlServer.SqlServerConnection.FetchNextJob(String[] queues, CancellationToken cancellationToken)
   at Hangfire.Server.Worker.Execute(BackgroundProcessContext context)
   at Hangfire.Server.ServerProcessExtensions.Execute(IServerProcess process, BackgroundProcessContext context)
   at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)
ClientConnectionId:acc48f04-0c95-4acf-87ea-d46b24321996
Error Number:233,State:0,Class:20



[2017-04-24 08:54:42,343]  Error occurred during execution of 'ServerHeartbeat' process. Execution will be retried (attempt #4) in 00:00:09 seconds.
System.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: Shared Memory Provider, error: 0 - No process is on the other end of the pipe.) ---> System.ComponentModel.Win32Exception (0x80004005): No process is on the other end of the pipe
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Hangfire.SqlServer.SqlServerStorage.CreateAndOpenConnection()
   at Hangfire.SqlServer.SqlServerStorage.UseConnection[T](Func`2 func)
   at Hangfire.SqlServer.SqlServerStorage.UseConnection(Action`1 action)
   at Hangfire.SqlServer.SqlServerConnection.Heartbeat(String serverId)
   at Hangfire.Server.ServerHeartbeat.Execute(BackgroundProcessContext context)
   at Hangfire.Server.ServerProcessExtensions.Execute(IServerProcess process, BackgroundProcessContext context)
   at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)
ClientConnectionId:2118d211-2ce9-4b83-8894-f4e1f44c6ff9
Error Number:233,State:0,Class:20



[2017-04-24 08:54:42,342]  Error occurred during execution of 'Worker #52b6343e' process. Execution will be retried (attempt #4) in 00:00:15 seconds.
System.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: Shared Memory Provider, error: 0 - No process is on the other end of the pipe.) ---> System.ComponentModel.Win32Exception (0x80004005): No process is on the other end of the pipe
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Hangfire.SqlServer.SqlServerStorage.CreateAndOpenConnection()
   at Hangfire.SqlServer.SqlServerJobQueue.Dequeue(String[] queues, CancellationToken cancellationToken)
   at Hangfire.SqlServer.SqlServerConnection.FetchNextJob(String[] queues, CancellationToken cancellationToken)
   at Hangfire.Server.Worker.Execute(BackgroundProcessContext context)
   at Hangfire.Server.ServerProcessExtensions.Execute(IServerProcess process, BackgroundProcessContext context)
   at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)
ClientConnectionId:2118d211-2ce9-4b83-8894-f4e1f44c6ff9
Error Number:233,State:0,Class:20



[2017-04-24 08:54:42,341]  Error occurred during execution of 'Worker #562336de' process. Execution will be retried (attempt #4) in 00:00:13 seconds.
System.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: Shared Memory Provider, error: 0 - No process is on the other end of the pipe.) ---> System.ComponentModel.Win32Exception (0x80004005): No process is on the other end of the pipe
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Hangfire.SqlServer.SqlServerStorage.CreateAndOpenConnection()
   at Hangfire.SqlServer.SqlServerJobQueue.Dequeue(String[] queues, CancellationToken cancellationToken)
   at Hangfire.SqlServer.SqlServerConnection.FetchNextJob(String[] queues, CancellationToken cancellationToken)
   at Hangfire.Server.Worker.Execute(BackgroundProcessContext context)
   at Hangfire.Server.ServerProcessExtensions.Execute(IServerProcess process, BackgroundProcessContext context)
   at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)
ClientConnectionId:acc48f04-0c95-4acf-87ea-d46b24321996
Error Number:233,State:0,Class:20



[2017-04-24 08:54:42,316]  Error occurred during execution of 'Worker #a5abe107' process. Execution will be retried (attempt #4) in 00:00:15 seconds.
System.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: Shared Memory Provider, error: 0 - No process is on the other end of the pipe.) ---> System.ComponentModel.Win32Exception (0x80004005): No process is on the other end of the pipe
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Hangfire.SqlServer.SqlServerStorage.CreateAndOpenConnection()
   at Hangfire.SqlServer.SqlServerJobQueue.Dequeue(String[] queues, CancellationToken cancellationToken)
   at Hangfire.SqlServer.SqlServerConnection.FetchNextJob(String[] queues, CancellationToken cancellationToken)
   at Hangfire.Server.Worker.Execute(BackgroundProcessContext context)
   at Hangfire.Server.ServerProcessExtensions.Execute(IServerProcess process, BackgroundProcessContext context)
   at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)
ClientConnectionId:2118d211-2ce9-4b83-8894-f4e1f44c6ff9
Error Number:233,State:0,Class:20



[2017-04-24 08:54:42,341]  Error occurred during execution of 'Worker #6056a04c' process. Execution will be retried (attempt #4) in 00:00:13 seconds.
System.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: Shared Memory Provider, error: 0 - No process is on the other end of the pipe.) ---> System.ComponentModel.Win32Exception (0x80004005): No process is on the other end of the pipe
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Hangfire.SqlServer.SqlServerStorage.CreateAndOpenConnection()
   at Hangfire.SqlServer.SqlServerJobQueue.Dequeue(String[] queues, CancellationToken cancellationToken)
   at Hangfire.SqlServer.SqlServerConnection.FetchNextJob(String[] queues, CancellationToken cancellationToken)
   at Hangfire.Server.Worker.Execute(BackgroundProcessContext context)
   at Hangfire.Server.ServerProcessExtensions.Execute(IServerProcess process, BackgroundProcessContext context)
   at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)
ClientConnectionId:2118d211-2ce9-4b83-8894-f4e1f44c6ff9
Error Number:233,State:0,Class:20



[2017-04-24 08:54:42,339]  Error occurred during execution of 'Worker #5eeb558e' process. Execution will be retried (attempt #4) in 00:00:15 seconds.
System.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: Shared Memory Provider, error: 0 - No process is on the other end of the pipe.) ---> System.ComponentModel.Win32Exception (0x80004005): No process is on the other end of the pipe
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Hangfire.SqlServer.SqlServerStorage.CreateAndOpenConnection()
   at Hangfire.SqlServer.SqlServerJobQueue.Dequeue(String[] queues, CancellationToken cancellationToken)
   at Hangfire.SqlServer.SqlServerConnection.FetchNextJob(String[] queues, CancellationToken cancellationToken)
   at Hangfire.Server.Worker.Execute(BackgroundProcessContext context)
   at Hangfire.Server.ServerProcessExtensions.Execute(IServerProcess process, BackgroundProcessContext context)
   at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)
ClientConnectionId:acc48f04-0c95-4acf-87ea-d46b24321996
Error Number:233,State:0,Class:20



[2017-04-24 08:54:42,333]  Error occurred during execution of 'Worker #6ea57a45' process. Execution will be retried (attempt #4) in 00:00:13 seconds.
System.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: Shared Memory Provider, error: 0 - No process is on the other end of the pipe.) ---> System.ComponentModel.Win32Exception (0x80004005): No process is on the other end of the pipe
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Hangfire.SqlServer.SqlServerStorage.CreateAndOpenConnection()
   at Hangfire.SqlServer.SqlServerJobQueue.Dequeue(String[] queues, CancellationToken cancellationToken)
   at Hangfire.SqlServer.SqlServerConnection.FetchNextJob(String[] queues, CancellationToken cancellationToken)
   at Hangfire.Server.Worker.Execute(BackgroundProcessContext context)
   at Hangfire.Server.ServerProcessExtensions.Execute(IServerProcess process, BackgroundProcessContext context)
   at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)
ClientConnectionId:2118d211-2ce9-4b83-8894-f4e1f44c6ff9
Error Number:233,State:0,Class:20



[2017-04-24 08:54:42,333]  Error occurred during execution of 'Worker #0e4bfb6b' process. Execution will be retried (attempt #4) in 00:00:10 seconds.
System.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: Shared Memory Provider, error: 0 - No process is on the other end of the pipe.) ---> System.ComponentModel.Win32Exception (0x80004005): No process is on the other end of the pipe
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Hangfire.SqlServer.SqlServerStorage.CreateAndOpenConnection()
   at Hangfire.SqlServer.SqlServerJobQueue.Dequeue(String[] queues, CancellationToken cancellationToken)
   at Hangfire.SqlServer.SqlServerConnection.FetchNextJob(String[] queues, CancellationToken cancellationToken)
   at Hangfire.Server.Worker.Execute(BackgroundProcessContext context)
   at Hangfire.Server.ServerProcessExtensions.Execute(IServerProcess process, BackgroundProcessContext context)
   at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)
ClientConnectionId:2118d211-2ce9-4b83-8894-f4e1f44c6ff9
Error Number:233,State:0,Class:20



[2017-04-24 08:54:42,333]  Error occurred during execution of 'Worker #be775442' process. Execution will be retried (attempt #4) in 00:00:11 seconds.
System.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: Shared Memory Provider, error: 0 - No process is on the other end of the pipe.) ---> System.ComponentModel.Win32Exception (0x80004005): No process is on the other end of the pipe
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Hangfire.SqlServer.SqlServerStorage.CreateAndOpenConnection()
   at Hangfire.SqlServer.SqlServerJobQueue.Dequeue(String[] queues, CancellationToken cancellationToken)
   at Hangfire.SqlServer.SqlServerConnection.FetchNextJob(String[] queues, CancellationToken cancellationToken)
   at Hangfire.Server.Worker.Execute(BackgroundProcessContext context)
   at Hangfire.Server.ServerProcessExtensions.Execute(IServerProcess process, BackgroundProcessContext context)
   at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)
ClientConnectionId:acc48f04-0c95-4acf-87ea-d46b24321996
Error Number:233,State:0,Class:20



[2017-04-24 08:54:42,332]  Error occurred during execution of 'Worker #50430aef' process. Execution will be retried (attempt #4) in 00:00:12 seconds.
System.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: Shared Memory Provider, error: 0 - No process is on the other end of the pipe.) ---> System.ComponentModel.Win32Exception (0x80004005): No process is on the other end of the pipe
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Hangfire.SqlServer.SqlServerStorage.CreateAndOpenConnection()
   at Hangfire.SqlServer.SqlServerJobQueue.Dequeue(String[] queues, CancellationToken cancellationToken)
   at Hangfire.SqlServer.SqlServerConnection.FetchNextJob(String[] queues, CancellationToken cancellationToken)
   at Hangfire.Server.Worker.Execute(BackgroundProcessContext context)
   at Hangfire.Server.ServerProcessExtensions.Execute(IServerProcess process, BackgroundProcessContext context)
   at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)
ClientConnectionId:2118d211-2ce9-4b83-8894-f4e1f44c6ff9
Error Number:233,State:0,Class:20



[2017-04-24 08:54:42,329]  Error occurred during execution of 'Worker #866fea96' process. Execution will be retried (attempt #4) in 00:00:11 seconds.
System.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: Shared Memory Provider, error: 0 - No process is on the other end of the pipe.) ---> System.ComponentModel.Win32Exception (0x80004005): No process is on the other end of the pipe
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Hangfire.SqlServer.SqlServerStorage.CreateAndOpenConnection()
   at Hangfire.SqlServer.SqlServerJobQueue.Dequeue(String[] queues, CancellationToken cancellationToken)
   at Hangfire.SqlServer.SqlServerConnection.FetchNextJob(String[] queues, CancellationToken cancellationToken)
   at Hangfire.Server.Worker.Execute(BackgroundProcessContext context)
   at Hangfire.Server.ServerProcessExtensions.Execute(IServerProcess process, BackgroundProcessContext context)
   at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)
ClientConnectionId:2118d211-2ce9-4b83-8894-f4e1f44c6ff9
Error Number:233,State:0,Class:20



[2017-04-24 08:54:42,329]  Error occurred during execution of 'Worker #cbcdf468' process. Execution will be retried (attempt #4) in 00:00:11 seconds.
System.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: Shared Memory Provider, error: 0 - No process is on the other end of the pipe.) ---> System.ComponentModel.Win32Exception (0x80004005): No process is on the other end of the pipe
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Hangfire.SqlServer.SqlServerStorage.CreateAndOpenConnection()
   at Hangfire.SqlServer.SqlServerJobQueue.Dequeue(String[] queues, CancellationToken cancellationToken)
   at Hangfire.SqlServer.SqlServerConnection.FetchNextJob(String[] queues, CancellationToken cancellationToken)
   at Hangfire.Server.Worker.Execute(BackgroundProcessContext context)
   at Hangfire.Server.ServerProcessExtensions.Execute(IServerProcess process, BackgroundProcessContext context)
   at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)
ClientConnectionId:2118d211-2ce9-4b83-8894-f4e1f44c6ff9
Error Number:233,State:0,Class:20



[2017-04-24 08:54:42,328]  Error occurred during execution of 'Worker #8549098d' process. Execution will be retried (attempt #4) in 00:00:09 seconds.
System.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: Shared Memory Provider, error: 0 - No process is on the other end of the pipe.) ---> System.ComponentModel.Win32Exception (0x80004005): No process is on the other end of the pipe
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Hangfire.SqlServer.SqlServerStorage.CreateAndOpenConnection()
   at Hangfire.SqlServer.SqlServerJobQueue.Dequeue(String[] queues, CancellationToken cancellationToken)
   at Hangfire.SqlServer.SqlServerConnection.FetchNextJob(String[] queues, CancellationToken cancellationToken)
   at Hangfire.Server.Worker.Execute(BackgroundProcessContext context)
   at Hangfire.Server.ServerProcessExtensions.Execute(IServerProcess process, BackgroundProcessContext context)
   at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)
ClientConnectionId:acc48f04-0c95-4acf-87ea-d46b24321996
Error Number:233,State:0,Class:20



[2017-04-24 08:54:42,325]  Error occurred during execution of 'Worker #3949db42' process. Execution will be retried (attempt #4) in 00:00:09 seconds.
System.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: Shared Memory Provider, error: 0 - No process is on the other end of the pipe.) ---> System.ComponentModel.Win32Exception (0x80004005): No process is on the other end of the pipe
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Hangfire.SqlServer.SqlServerStorage.CreateAndOpenConnection()
   at Hangfire.SqlServer.SqlServerJobQueue.Dequeue(String[] queues, CancellationToken cancellationToken)
   at Hangfire.SqlServer.SqlServerConnection.FetchNextJob(String[] queues, CancellationToken cancellationToken)
   at Hangfire.Server.Worker.Execute(BackgroundProcessContext context)
   at Hangfire.Server.ServerProcessExtensions.Execute(IServerProcess process, BackgroundProcessContext context)
   at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)
ClientConnectionId:acc48f04-0c95-4acf-87ea-d46b24321996
Error Number:233,State:0,Class:20



[2017-04-24 08:54:42,324]  Error occurred during execution of 'Worker #fdb214ac' process. Execution will be retried (attempt #4) in 00:00:10 seconds.
System.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: Shared Memory Provider, error: 0 - No process is on the other end of the pipe.) ---> System.ComponentModel.Win32Exception (0x80004005): No process is on the other end of the pipe
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Hangfire.SqlServer.SqlServerStorage.CreateAndOpenConnection()
   at Hangfire.SqlServer.SqlServerJobQueue.Dequeue(String[] queues, CancellationToken cancellationToken)
   at Hangfire.SqlServer.SqlServerConnection.FetchNextJob(String[] queues, CancellationToken cancellationToken)
   at Hangfire.Server.Worker.Execute(BackgroundProcessContext context)
   at Hangfire.Server.ServerProcessExtensions.Execute(IServerProcess process, BackgroundProcessContext context)
   at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)
ClientConnectionId:2118d211-2ce9-4b83-8894-f4e1f44c6ff9
Error Number:233,State:0,Class:20



[2017-04-24 08:54:42,324]  Error occurred during execution of 'Worker #d5476016' process. Execution will be retried (attempt #4) in 00:00:14 seconds.
System.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: Shared Memory Provider, error: 0 - No process is on the other end of the pipe.) ---> System.ComponentModel.Win32Exception (0x80004005): No process is on the other end of the pipe
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Hangfire.SqlServer.SqlServerStorage.CreateAndOpenConnection()
   at Hangfire.SqlServer.SqlServerJobQueue.Dequeue(String[] queues, CancellationToken cancellationToken)
   at Hangfire.SqlServer.SqlServerConnection.FetchNextJob(String[] queues, CancellationToken cancellationToken)
   at Hangfire.Server.Worker.Execute(BackgroundProcessContext context)
   at Hangfire.Server.ServerProcessExtensions.Execute(IServerProcess process, BackgroundProcessContext context)
   at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)
ClientConnectionId:acc48f04-0c95-4acf-87ea-d46b24321996
Error Number:233,State:0,Class:20



[2017-04-24 08:54:42,321]  Error occurred during execution of 'Worker #21a89c9e' process. Execution will be retried (attempt #4) in 00:00:11 seconds.
System.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: Shared Memory Provider, error: 0 - No process is on the other end of the pipe.) ---> System.ComponentModel.Win32Exception (0x80004005): No process is on the other end of the pipe
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Hangfire.SqlServer.SqlServerStorage.CreateAndOpenConnection()
   at Hangfire.SqlServer.SqlServerJobQueue.Dequeue(String[] queues, CancellationToken cancellationToken)
   at Hangfire.SqlServer.SqlServerConnection.FetchNextJob(String[] queues, CancellationToken cancellationToken)
   at Hangfire.Server.Worker.Execute(BackgroundProcessContext context)
   at Hangfire.Server.ServerProcessExtensions.Execute(IServerProcess process, BackgroundProcessContext context)
   at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)
ClientConnectionId:2118d211-2ce9-4b83-8894-f4e1f44c6ff9
Error Number:233,State:0,Class:20



[2017-04-24 08:54:42,319]  Error occurred during execution of 'Worker #c1ec3380' process. Execution will be retried (attempt #4) in 00:00:12 seconds.
System.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: Shared Memory Provider, error: 0 - No process is on the other end of the pipe.) ---> System.ComponentModel.Win32Exception (0x80004005): No process is on the other end of the pipe
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Hangfire.SqlServer.SqlServerStorage.CreateAndOpenConnection()
   at Hangfire.SqlServer.SqlServerJobQueue.Dequeue(String[] queues, CancellationToken cancellationToken)
   at Hangfire.SqlServer.SqlServerConnection.FetchNextJob(String[] queues, CancellationToken cancellationToken)
   at Hangfire.Server.Worker.Execute(BackgroundProcessContext context)
   at Hangfire.Server.ServerProcessExtensions.Execute(IServerProcess process, BackgroundProcessContext context)
   at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)
ClientConnectionId:acc48f04-0c95-4acf-87ea-d46b24321996
Error Number:233,State:0,Class:20



[2017-04-24 08:54:42,319]  Error occurred during execution of 'Worker #e760f7bf' process. Execution will be retried (attempt #4) in 00:00:09 seconds.
System.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: Shared Memory Provider, error: 0 - No process is on the other end of the pipe.) ---> System.ComponentModel.Win32Exception (0x80004005): No process is on the other end of the pipe
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Hangfire.SqlServer.SqlServerStorage.CreateAndOpenConnection()
   at Hangfire.SqlServer.SqlServerJobQueue.Dequeue(String[] queues, CancellationToken cancellationToken)
   at Hangfire.SqlServer.SqlServerConnection.FetchNextJob(String[] queues, CancellationToken cancellationToken)
   at Hangfire.Server.Worker.Execute(BackgroundProcessContext context)
   at Hangfire.Server.ServerProcessExtensions.Execute(IServerProcess process, BackgroundProcessContext context)
   at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)
ClientConnectionId:acc48f04-0c95-4acf-87ea-d46b24321996
Error Number:233,State:0,Class:20



[2017-04-24 08:54:42,318]  Error occurred during execution of 'Worker #ee246142' process. Execution will be retried (attempt #4) in 00:00:10 seconds.
System.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: Shared Memory Provider, error: 0 - No process is on the other end of the pipe.) ---> System.ComponentModel.Win32Exception (0x80004005): No process is on the other end of the pipe
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Hangfire.SqlServer.SqlServerStorage.CreateAndOpenConnection()
   at Hangfire.SqlServer.SqlServerJobQueue.Dequeue(String[] queues, CancellationToken cancellationToken)
   at Hangfire.SqlServer.SqlServerConnection.FetchNextJob(String[] queues, CancellationToken cancellationToken)
   at Hangfire.Server.Worker.Execute(BackgroundProcessContext context)
   at Hangfire.Server.ServerProcessExtensions.Execute(IServerProcess process, BackgroundProcessContext context)
   at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)
ClientConnectionId:acc48f04-0c95-4acf-87ea-d46b24321996
Error Number:233,State:0,Class:20



[2017-04-24 08:54:42,316]  Error occurred during execution of 'DelayedJobScheduler' process. Execution will be retried (attempt #4) in 00:00:10 seconds.
System.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: Shared Memory Provider, error: 0 - No process is on the other end of the pipe.) ---> System.ComponentModel.Win32Exception (0x80004005): No process is on the other end of the pipe
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Hangfire.SqlServer.SqlServerStorage.CreateAndOpenConnection()
   at Hangfire.SqlServer.SqlServerDistributedLock..ctor(SqlServerStorage storage, String resource, TimeSpan timeout)
   at Hangfire.SqlServer.SqlServerConnection.AcquireDistributedLock(String resource, TimeSpan timeout)
   at Hangfire.Server.DelayedJobScheduler.EnqueueNextScheduledJob(BackgroundProcessContext context)
   at Hangfire.Server.DelayedJobScheduler.Execute(BackgroundProcessContext context)
   at Hangfire.Server.ServerProcessExtensions.Execute(IServerProcess process, BackgroundProcessContext context)
   at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)
ClientConnectionId:2118d211-2ce9-4b83-8894-f4e1f44c6ff9
Error Number:233,State:0,Class:20



[2017-04-24 08:59:11,433]  Error occurred during execution of 'ServerHeartbeat' process. Execution will be retried (attempt #5) in 00:00:21 seconds.
System.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: Shared Memory Provider, error: 0 - No process is on the other end of the pipe.) ---> System.ComponentModel.Win32Exception (0x80004005): No process is on the other end of the pipe
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Hangfire.SqlServer.SqlServerStorage.CreateAndOpenConnection()
   at Hangfire.SqlServer.SqlServerStorage.UseConnection[T](Func`2 func)
   at Hangfire.SqlServer.SqlServerStorage.UseConnection(Action`1 action)
   at Hangfire.SqlServer.SqlServerConnection.Heartbeat(String serverId)
   at Hangfire.Server.ServerHeartbeat.Execute(BackgroundProcessContext context)
   at Hangfire.Server.ServerProcessExtensions.Execute(IServerProcess process, BackgroundProcessContext context)
   at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)
ClientConnectionId:2118d211-2ce9-4b83-8894-f4e1f44c6ff9
Error Number:233,State:0,Class:20



